# version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    env_file: .env
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      - POSTGRES_DB=geosoil
      - POSTGRES_USER=magayendiaye
      - POSTGRES_PASSWORD=DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  geosoil:
    build: ./geosoil
    platform: linux/amd64
    command: gunicorn geosoil.wsgi:application --workers 4 --bind 0.0.0.0:8000 --reload --timeout 120
    env_file: .env
    volumes:
      - ./geosoil:/app
      - ./data:/data          
      - ./models:/models     
    depends_on:
      - db
    ports:
      - "8000:8000"

  #cron:
  #  build: ./geosoil             
  #  entrypoint: ["/bin/sh","-c","cron -f"]
  #  env_file: .env
  #  volumes:
  #    - ./web:/app
  #    - ./data:/data
  #    - ./models:/models
  #    - ./cron/soc_cron:/etc/cron.d/soc_cron   
  #  depends_on:
  #    - db

volumes:
  postgres_data:
