# Generated by Django 5.2.1 on 2025-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilprofile',
            old_name='sentinel_data',
            new_name='teledection_data',
        ),
    ]
